dist: xenial
sudo: required
language: node_js
node_js:
- 8.11.3
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
install:
- sudo apt-get install -qq g++-8
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
- git clone https://github.com/emscripten-core/emsdk.git && cd emsdk && git pull &&
  ./emsdk install sdk-1.38.48  && ./emsdk activate sdk-1.38.48 && . ./emsdk_env.sh && cd ..
- git submodule init
- git submodule update
script:
- make web
after_success:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- cd web
- git init
- git remote add origin https://${GH_TOKEN}@github.com/Oliver-BE/sorting-algorithms-d3.git
  > /dev/null 2>&1
- git checkout -b gh-pages
- git add .
- git commit --message "Travis build ${TRAVIS_BUILD_NUMBER}"
- test ${TRAVIS_BRANCH} = "master" && git push --force --quiet origin gh-pages
env:
  global:
    secure: ZK2X9W/GdStf1tooW7Xx4VBUbWexykBN4df8Xn7eZ9JloYrS1hbrZ5NZ2zqNbvM8tDhOJqf7j9VSr/BzQqsDRi6Hc5xGVcNf/RpnyHfMrRrzr1Xwm1WY/fxarEKoVgaxKybplTqg8X3wARZ735RL7PA8454AQmHy5/2506Cn6orSPFzgUOSXp3iIlW6ZSPslX+sZ0mRPZ/D+8evOWXNCxXW1/AjnP6hmEg1Vv03etJm36VeSd9DLTn+Ikmojn2N4aCwjQOZVkU2eAyuNTxelFw/J0lPNenINdGXqcr8BXWFFStBK8K8vor6QLkEZj23sH3acX6ZYjkosOumn7AzYrFhfGbUGOBNrp9AAyHfo56Dke7NFHONq2Fb6sAzRxdPOyE/72wc4d4r62HKOI8n5wVR16PEMT8O5OM6wO9JVvGttfD74wdCAvY1/zGOb+VtrE0fnQrizeIlDSK0trFX7Xs0mpf4RuU9d9Vflx3owBDUbjYShvZtH5GCiLdL+7reetxd9wK19DcV9a/jmcpmwC5VWTeF5fKN4NAOIbSJsRd6xwZ7jCM8Sr3XgNes+CIfvdy0LhQY23KJ8dnxhboGNUZk9V1ODINwVIurVzGSrf7VhPnq8qapnt+3gMuO8vAO8Cu0fbiruEowyOY2mhj1tkJoRjykozetcUN5PG+eH1Uw=
